services:
  - type: worker
    name: legal-bot-worker
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: python bot.py
    envVars:
      - key: BOT_TOKEN
        value: 8285727455:AAHZ3X8s7enoZC5csZxryGnZGuxSe-3Naig
